# プロジェクト設定
project_id = "nexia-app"

# API設定
[api]
# APIのポート
port = 54321
# 匿名キー (注：これはサンプルキー。本番環境では必ず変更してください)
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
# サービスロールキー (注：これはサンプルキー。本番環境では必ず変更してください)
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

# データベース設定
[db]
# 最大接続数
max_connections = 100
# ポート
port = 54322
# JWTシークレット (注：本番環境では必ず変更してください)
jwt_secret = "your-super-secret-jwt-token-with-at-least-32-characters-long"

# Studio設定
[studio]
# ポート
port = 54323
# 管理者ユーザー名
admin_username = "supabase"
# 管理者パスワード (注：本番環境では必ず変更してください)
admin_password = "this_password_is_insecure_and_should_be_updated" 